#! /bin/bash

killall "sxhkd" &
sxhkd &
nitrogen --restore &&
picom -b &
kitty &
flameshot &
bash /home/erio/.config/polybar/launch.sh --forest &
dunst -conf ~/.config/dunst/dunstrc &
export _JAVA_AWT_WM_NONREPARENTING=1



bspc config border_width         2
bspc config normal_border_color  '#adadad'
bspc config focused_border_color '#ffb0c8'
bspc config top_padding 	40
bspc config bottom_padding 	4
bspc config left_padding 	4
bspc config right_padding 	4

bspc config honor_size_hints	true

bspc config window_gap          10
bspc config split_ratio          	0.55
bspc config borderless_monocle   	true
bspc config gapless_monocle      	false

bspc config ignore_ewmh_focus 		false

bspc rule -a rofi state=floating
bspc rule -a Nitrogen state=floating



setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl
#hsetroot -add '#FF7349' -add '#AF3309' -add '#A82126' -add '#631009' -grad>

if [[ $(xrandr -q | grep HDMI-0) ]]; then
    xrandr --output DP-0 --primary --mode 2560x1440 --rotate normal --output HDMI-0 --nonprimary --mode 1440x900 --pos 0x500 --rotate normal --left-of DP-0
fi

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 0

~
